medallion_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '/Users/damianilkow/Desktop/Dami/Master_IA/09_ing_de_software_y_datos/examenes/examen_2/UdeSA-Ing-DBT-Airflow/warehouse/medallion.duckdb') }}"
      threads: 4
      extensions: ["parquet"]
